### ISSUE TITLE
Only works in default browser on MacOS, but that is not documented

### ISSUE THREAD

**Issue by brian-kephart** [WICG/pwa-url-handler#32]
After trying and failing to get this function to work in Chrome, I tried installing the PWA in my default browser (Brave) and it worked immediately. It appears that this feature only works in the default browser, but that is not specified in the documentation anywhere that I have found. I am using MacOS 11.5.2.

**Comment by LuHuangMSFT** [comment]
@brian-kephart Thanks for trying this out. We tried our best to reference "default browser" throughout the explainer text.

**Comment by brian-kephart** [comment]
I implemented via [these instructions](https://web.dev/pwa-url-handler/), which I'm just now realizing come from a different organization. That page directed me here for comments, so I think I filed this in the wrong place. Sorry for the confusion, and thanks for the quick response!

**Comment by tomayac** [comment]
@brian-kephart I have clarified our documentation in https://github.com/GoogleChrome/web.dev/pull/6163. Thanks for bringing this up!

**Comment by LuHuangMSFT** [comment]
Thanks @tomayac!
